Leuta task2
denisleuta/spbu-python-course pull request #2
Opened 2024-10-08 19:25 UTC by denisleuta

Этот код реализует функции и декораторы для каррирования, кэширования результатов, отложенной оценки и изоляции аргументов.
1. Каррирование
curry_explicit(function, arity): Преобразует функцию с несколькими параметрами в последовательность функций, каждая из которых принимает один параметр. Проверяет корректность арности и выбрасывает исключения при ошибках.
uncurry_explicit(function, arity): Обратная операция к каррированию, преобразующая каррированную функцию обратно в обычную.
2. Кэширование результатов
cache_results(max_size=0): Декоратор для кэширования результатов выполнения функции. Поддерживает как позиционные, так и именованные аргументы.
3. Отложенная оценка и изоляция аргументов
Классы Evaluated и Isolated:
Evaluated вычисляет значения по умолчанию в момент вызова.
Isolated создает глубокую копию переданного значения.
smart_args(enable_positional=True): Декоратор для гибкой обработки аргументов функции, анализирующий типы значений по умолчанию.

2024-10-09 13:38 UTC, Krekep requested changes
Необходимы исправления

2024-10-09 13:38 UTC, Krekep commented on project/cache.py
> +def cache_results(max_size=0):
Необходимо указать у `max_size` typehint

2024-10-09 13:38 UTC, Krekep commented on project/curry.py
> +def curry_explicit(function, arity):
Необходимы typehints

2024-10-09 13:38 UTC, Krekep commented on project/smart_args.py
> +            func_spec = inspect.getfullargspec(func)
Зачем Вам каждый раз получать полную информацию о функции, которая не меняется?

2024-10-09 13:38 UTC, Krekep commented on tests/test_cache.py
> +    assert add(5, 6) == 11  # Should still be cached
Вы проверили, что функция сложения двух чисел, обёрнутая в Ваш декоратор по прежнему корректно складывает числа.
Вы никак не продемонстрировали, что кэш действительно работает

2024-10-09 13:38 UTC, Krekep commented on tests/test_cache.py
> +    assert add(1000000, 2000000) == 3000000  # Large integers
Тест на сложение двух целых чисел уже есть выше

2024-10-09 13:38 UTC, Krekep commented on tests/test_cache.py
Не хватает тестов:
- со встроенными в Python функциями;
- с нехешируемыми аргументами;
- демонстрирующих кэш после i-той итерации

2024-10-09 13:38 UTC, Krekep commented on tests/test_curry.py
Как минимум не хватает тестов для встроенных в Python функций

2024-10-09 13:38 UTC, Krekep commented on tests/test_smart_args.py
> +    ), "Result should be a random number between 1 and 10."
Этот тест не показывает, что Evaluated вычисляет значение каждый раз при вызове функции

2024-10-09 13:38 UTC, Krekep commented on tests/test_smart_args.py
> +    ), "Both keyword arguments should override default values."
А если вызвать, к примеру, `my_function(3)`?

2024-10-09 13:38 UTC, Krekep commented on tests/test_smart_args.py
Добавьте тесты из условия задачи.

2024-10-10 12:01 UTC, denisleuta commented on project/cache.py
> +def cache_results(max_size=0):
Понял, исправлю

2024-10-10 12:01 UTC, denisleuta commented on project/curry.py
> +def curry_explicit(function, arity):
Понял, исправлю

2024-10-10 12:10 UTC, denisleuta commented on project/smart_args.py
> +            func_spec = inspect.getfullargspec(func)
Ошибся, исправлю

2024-10-12 19:04 UTC, denisleuta commented on tests/test_cache.py
> +    assert add(5, 6) == 11  # Should still be cached
Добавил демонстрацию

2024-10-12 19:04 UTC, denisleuta commented on tests/test_cache.py
> +    assert add(1000000, 2000000) == 3000000  # Large integers
Убрал

2024-10-12 19:04 UTC, denisleuta commented on tests/test_cache.py
Добавил тесты

2024-10-12 19:04 UTC, denisleuta commented on tests/test_curry.py
Добавил данный тест

2024-10-12 19:05 UTC, denisleuta commented on tests/test_smart_args.py
> +    ), "Result should be a random number between 1 and 10."
Ошибся

2024-10-12 19:05 UTC, denisleuta commented on tests/test_smart_args.py
> +    ), "Both keyword arguments should override default values."
Исправил

2024-10-12 19:05 UTC, denisleuta commented on tests/test_smart_args.py
Добавил

2024-10-14 14:40 UTC, Krekep requested changes
Необходимы исправления

2024-10-14 14:40 UTC, Krekep commented on project/cache.py
> +            print(f"Cache miss: {args}, kwargs: {kwargs} - calculating")
Пользователь не ожидает вывода (побочного действия) от декоратора кэширования. Вывод лучше сделать опциональной возможностью

2024-10-14 14:40 UTC, Krekep commented on project/curry.py
> +            )
Выглядит некорректно. На вход функции подаётся набор аргументов, переданных пользователем, без их упаковки в массив.
`sum` принимает максимум два аргумента --- коллекцию и откуда начать.

2024-10-14 14:40 UTC, Krekep commented on project/curry.py
> +        return lambda *x: curry_helper(args + list(x))
Каррирование превращает функцию от `n` аргументов в `n` функций от одного аргумента. Насколько я вижу у Вас будет работать следующее:
```
f = curry_explicit(print, 2)
f(1, 2)()
```
Что является некорректным примером работы с каррированной функцией.

2024-10-14 14:40 UTC, Krekep commented on tests/test_cache.py
> +    assert built_in_sum([4, 5]) == 9  # Cache miss
Тут тоже надо показать, что в кэше есть/отсутствуют указанные аргументы

2024-10-14 14:40 UTC, Krekep commented on tests/test_cache.py
> +    assert list_sum([1, 2, 3]) == 6  # Cache hit
И тут

2024-10-14 14:40 UTC, Krekep commented on tests/test_cache.py
> +    assert len(iterations) == 4  # Ensure each call is tracked
Добавьте сюда для наглядности track_iterations(3, 4). В таком случае тест покажет, что, при нахождении аргументов в кэше, не будут вычислено тело функции

2024-10-14 14:40 UTC, Krekep commented on tests/test_curry.py
> +    assert curried_sum(1, 2) == 3  # Check multiple argument application
Тест `curried_sum(1, 2)` не должен проходить, т.к. это некорректное использование каррированной функции

2024-10-14 14:40 UTC, Krekep commented on tests/test_smart_args.py
> +    assert result1 != result2, "Results should differ for each function call."
Это неправда

2024-10-14 14:40 UTC, Krekep commented on tests/test_smart_args.py
> +    assert original_data == [], "Original data should remain unchanged."
Ну, Вы тут и не меняли original_data, так что тест выглядит странно

2024-10-14 14:40 UTC, Krekep commented on tests/test_smart_args.py
> +    ), "Both positional arguments should override default values."
У Вас выше написан такой же тест

2024-10-14 14:40 UTC, Krekep commented on tests/test_smart_args.py
Но Вы же не добавили их. 
Также не хватает тестов с keyword-only аргументами.

2024-10-14 14:40 UTC, Krekep commented on tests/test_smart_args.py
> +    ), "Should raise ValueError when using Isolated without providing an argument."
Этот тест не проверяет, что Вы не можете использовать Evaluated с Isolated вместе. Он проверяет, что если вместо Isolated не передать аргумент, функция упадёт с ошибкой, а такой тест у Вас уже выше написан.
Также на всякий случай уточню, что в данном случае `my_function` корректно объявлена

2024-10-16 20:54 UTC, denisleuta commented on tests/test_smart_args.py
Сейчас точно добавил

2024-10-16 20:54 UTC, denisleuta commented on project/cache.py
> +            print(f"Cache miss: {args}, kwargs: {kwargs} - calculating")
исправил

2024-10-16 20:54 UTC, denisleuta commented on project/curry.py
> +            )
исправил

2024-10-16 20:54 UTC, denisleuta commented on project/curry.py
> +        return lambda *x: curry_helper(args + list(x))
исправил

2024-10-16 20:55 UTC, denisleuta commented on tests/test_cache.py
> +    assert built_in_sum([4, 5]) == 9  # Cache miss
указал

2024-10-16 20:55 UTC, denisleuta commented on tests/test_cache.py
> +    assert list_sum([1, 2, 3]) == 6  # Cache hit
указал

2024-10-16 20:55 UTC, denisleuta commented on tests/test_cache.py
> +    assert len(iterations) == 4  # Ensure each call is tracked
Добавил

2024-10-16 20:56 UTC, denisleuta commented on tests/test_curry.py
> +    assert curried_sum(1, 2) == 3  # Check multiple argument application
Ой, ошибся, убрал данный тест

2024-10-16 20:56 UTC, denisleuta commented on tests/test_smart_args.py
> +    assert result1 != result2, "Results should differ for each function call."
изменил

2024-10-16 20:57 UTC, denisleuta commented on tests/test_smart_args.py
> +    assert original_data == [], "Original data should remain unchanged."
Исправил

2024-10-16 20:58 UTC, denisleuta commented on tests/test_smart_args.py
> +    ), "Both positional arguments should override default values."
убрал

2024-10-16 20:59 UTC, denisleuta commented on tests/test_smart_args.py
> +    ), "Should raise ValueError when using Isolated without providing an argument."
Изменил

2024-10-18 18:36 UTC, Krekep approved these changes
Зачтено

2024-10-19 17:25 UTC, merged