Leuta task4
denisleuta/spbu-python-course pull request #4
Opened 2024-10-22 08:39 UTC by denisleuta

Этот код реализует два ключевых элемента:

Класс ThreadPool — реализация пула потоков, который может параллельно выполнять задачи.
Функция sum_cartesian_product — вычисление суммы полного декартова произведения множеств целых чисел с использованием параллельных вычислений.

Класс ThreadPool управляет пулом потоков, которые параллельно обрабатывают задачи. Он работает следующим образом:

Конструктор __init__(self, num_threads: int):

Принимает количество потоков, которые должны быть запущены.
Инициализирует список задач (self.tasks), которые будут выполнены, и создаёт заданное количество потоков, каждый из которых запускает метод _worker.
Потоки работают в фоновом режиме (daemon = True), что позволяет завершить их, когда основной процесс завершён.

Метод _worker(self):

Это основной рабочий метод для каждого потока.
Поток ждёт задания (задачи) в очереди. Когда задача поступает, поток забирает её и выполняет.
Если пул завершает работу, поток выходит из цикла.

Метод enqueue(self, task: Callable[[], None]):

Добавляет новую задачу в очередь задач.
Если пул ещё не завершён (не вызван метод dispose), задача добавляется в список self.tasks, и ожидающие потоки уведомляются о новой задаче через условную переменную (self.condition).
Метод dispose(self):

Завершает работу пула потоков. Он уведомляет все потоки о том, что новые задачи не будут приняты.
После завершения всех задач метод ожидает завершения работы всех потоков с помощью thread.join().

Функция sum_cartesian_product

Эта функция вычисляет сумму всех комбинаций элементов из декартова произведения нескольких множеств с использованием параллельных вычислений.

Для создания декартова произведения используется функция itertools.product(*sets), которая генерирует все возможные комбинации элементов из переданных множеств.
Каждая комбинация передаётся в функцию sum_combination, которая просто суммирует элементы комбинации.
Параллельное вычисление суммы для каждой комбинации выполняется через ThreadPoolExecutor, который распределяет работу между потоками.
Результаты всех сумм собираются, и итоговая сумма возвращается как результат работы функции.

2024-10-22 09:52 UTC, Krekep requested changes
Необходимы исправления.

2024-10-22 09:52 UTC, Krekep commented on project/thread_pool.py
> +    return total_sum
Это отдельная от тредпула задача. Как по условию задачи, так и по смыслу кода

2024-10-22 09:52 UTC, Krekep commented on project/thread_pool.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Чем обоснован выбор `ThreadPoolExecutor`?

2024-10-22 09:52 UTC, Krekep commented on tests/test_thread_pool.py
> +    pool.dispose()
Как может быть больше 4?

2024-10-22 09:52 UTC, Krekep commented on tests/test_thread_pool.py
> +@pytest.mark.timeout(54)
Зачем Вам timeout на этот тест?

2024-10-22 09:52 UTC, Krekep commented on tests/test_thread_pool.py
> +    assert len(pool.threads) >= 4
С помощью `len` Вы проверите, что добавили 4 элемента в `threads`. Этот тест не проверяет, что у Вас действительно в пуле 4 работающих (активных) потока

2024-10-22 15:56 UTC, denisleuta commented on project/thread_pool.py
> +    return total_sum
Понял, перенес в другой файл

2024-10-22 15:57 UTC, denisleuta commented on project/thread_pool.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Не требуя явного управления потоками, как это было бы с использованием threading.Thread

2024-10-22 15:58 UTC, denisleuta commented on tests/test_thread_pool.py
> +    pool.dispose()
Никак не может быть. Исправил

2024-10-22 15:58 UTC, denisleuta commented on tests/test_thread_pool.py
> +@pytest.mark.timeout(54)
Хотел защитить от зависаний, убрал

2024-10-22 15:59 UTC, denisleuta commented on tests/test_thread_pool.py
> +    assert len(pool.threads) >= 4
Добавил проверку, чтобы было видно, что потоки активные

2024-10-22 17:07 UTC, Krekep commented on project/thread_pool.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
А чем Thread от Process отличаются? Почему Вы выбрали именно Thread для этой задачи?

2024-10-22 18:19 UTC, denisleuta commented on project/thread_pool.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Process не подвержены блокировке GIL, как напримр Thread, но для данной функции одного ядра вполне хватает т.к. потоки менее ресурсоемкие, так как он работают в одной области памяти.  В процессах наоборот, для каждого процесса создается своя область памяти и требуется межпроцессное взаимодействие для обмена данных. Так же потоки быстрее создаются и переключаются между задачами, что полезно для обработки множества небольших задач (например, суммирование комбинаций).

2024-10-23 07:26 UTC, Krekep commented on project/thread_pool.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Как Вы и написали, потоки подвержены блокировке GIL. А значит пока поток активно выполняется (к примеру, суммирует массив), другие потоки работать не будут. Поэтому для вычислительно-ёмких задач использовать потоки не имеет смысла.
Лучше уж в однопоточном режиме просуммировать, чтобы не было накладок на разбитие данных и переключение между потоками.

А ещё потоки исполняются на разных ядрах, но для данной задачи одного потока достаточно, это правда, т.к. суммирование простая операция

2024-10-23 16:59 UTC, denisleuta commented on project/thread_pool.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Я изменил функцию, теперь я использую процессы и задачи выполняются параллельно без блокировки

2024-10-25 09:41 UTC, Krekep approved these changes
Зачтено

2024-10-25 09:41 UTC, Krekep commented on project/sum_cartesian_product.py
> +    total_sum = sum(results)
В случае, если у Вас два больших множества размера `n`, то получится `n^2` пар, которые вы однопоточно сложите (сами пары параллельно, это правда).  Пусть `c` количество процессов в пуле.
Таким образом каждый процесс из пула выполнит `n^2 / c` операций --- суммирование пар, и однопоточно `n^2` --- суммирование массива, где каждый элемент сумма пары. Это грубая оценка
Если бы Вы разбили массив на `c` частей, то в параллельно бы выполнилось `2 * n^2/c` суммирований, и затем однопоточно бы осталось сложить `c` слагаемых, что вроде бы звучит быстрее

Возможно я где-то ошибся в рассуждениях выше, буду рад, если найдёте ошибку.
Это не замечание, просто комментарий

2024-10-25 09:41 UTC, Krekep commented on tests/test_thread_pool.py
> +        pool.enqueue(lambda i=i: task(i))
В чём смысл этой лямбды? Просто, Вы не первый, у кого я её вижу. Чтобы формально передавать Callable в функцию и mypy не ругался на несоответствие типов?

2024-10-28 19:29 UTC, merged