Leuta task5
denisleuta/spbu-python-course pull request #5
Opened 2024-10-29 16:17 UTC by denisleuta

Roulette Game Simulation
This project implements a simple simulation of a roulette game, featuring multiple bot players with distinct betting strategies. The game utilizes Python's object-oriented programming principles, employing metaclasses to dynamically register bot strategies and define game rules.

Key Components:
Bet Class: Represents a bet made by a bot, including the amount, type (color or number), and choice.

Bot Class: Serves as the base class for different bot strategies. Bots can place bets based on their defined strategies and manage their budgets.

Strategic Bots:

ConservativeBot: Always bets a fixed amount on "Red."
AggressiveBot: Bets a larger amount on a randomly selected number.
RandomBot: Randomly selects between a color or number bet.
OnlyGreenBot: Bets on the rare "Green" color.
Metaclasses:

StrategyMeta: A metaclass that dynamically registers different bot strategies. When a bot class is created, it automatically adds the bot to the strategies dictionary for easy access and management.
GameRuleMeta: A metaclass that configures game rules by defining essential constants, such as NUMBER_OF_FIELDS and WINNING_BUDGET, for the RouletteGame class, ensuring consistent game mechanics.
RouletteGame Class: Manages the game mechanics, including spinning the roulette wheel, evaluating bets, and displaying the current state of the game. It determines the outcome of each round and checks for winning conditions.

Features:
Simulates the spinning of a roulette wheel, randomly generating results for numbers and colors.
Evaluates bets based on the outcomes, adjusting the budgets of the bots accordingly.
Displays the game state after each round, providing insights into the budgets and actions of each bot.
Includes logic for determining a winner based on reaching a specified budget or all other bots being out of funds.
Testing:
The project includes a comprehensive test suite using pytest, covering:

Initialization and initial state of the game.
Proper functioning of the spin wheel and bet evaluations.
Progression through game rounds and accurate tracking of budgets.
Winning conditions based on bot budgets.
UML Diagram:
A UML diagram illustrating the design and relationships of the classes in this project is attached as rouletteUML.png.

2024-10-30 11:19 UTC, Krekep requested changes
Необходимы исправления

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
Сделайте декомпозицию этого файла

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +        self.choice = choice
На UML диаграмме эти поля отмечены приватными, но в коде их имена не соотносятся с принятым именованием non-public атрибутов

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +class Bot(metaclass=StrategyMeta):
Реализованные стратегии по факту являются одной и той же стратегией, замените/добавьте более сложную стратегию (к примеру, учитывающую историю ставок)

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +            return Bet(amount=10, bet_type="color", choice="Red")
Магические константы (в данном случае тип и выбор) следует заменить на более читаемый и отслеживаемый подход (нет, не на магические числа)

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +    WINNING_BUDGET: int = 1000  # Explicitly declare class attribute
В качестве условия победы, наверное, лучше считать количество оставшихся игроков, а не определённую сумму

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +            return bet.amount * 36
Почему 36? Ну и в целом в коде то тут, то там встречается магические константы, к которым такой же вопрос

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +            return Bet(amount=20, bet_type="color", choice="Green")
Если у бота 1 монетка, то он не должен обладать возможностью поставить 20

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +    def check_for_winner(self) -> Optional[Bot]:
Не хватает документации

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +    def play_round(self) -> None:
В этом методе не нужно опрашивать ботов, которые уже вылетели, о их желании поставить ставку

2024-10-30 11:19 UTC, Krekep commented on project/roulette.py
> +        return new_cls
Этот метакласс не добавляет новые стратегии, он просто запоминает в себе существующие и никак не использует их

2024-10-30 11:19 UTC, Krekep commented on roulette.png
1. Отношение наследования отображается другим способом
2. Как связаны GameRulesMeta и Bot? Про StrategyMeta и Game такой же вопрос
3. Между игрой и ботами отношение не ассоциации
4. Кажется, что между игрой и ставкой стрелка должна быть направлена в другую сторону
5. Почему `Bet` не связаны с `Bot`?
6. Идейно выглядит так, что, к примеру, `evaluate_bets` и `play_round` это приватные методы игры, которые не должны быть видны пользователю

2024-10-30 11:19 UTC, Krekep commented on tests/test_roulette.py
Не хватает тестов, проверяющих корректность работы метаклассов

2024-10-30 22:07 UTC, denisleuta commented on project/roulette.py
Сделал

2024-10-30 22:07 UTC, denisleuta commented on project/roulette.py
> +        self.choice = choice
Исправил

2024-10-30 22:08 UTC, denisleuta commented on project/roulette.py
> +class Bot(metaclass=StrategyMeta):
Добавил нового бота Strategy

2024-10-30 22:08 UTC, denisleuta commented on project/roulette.py
> +            return Bet(amount=10, bet_type="color", choice="Red")
Убрал эти константы

2024-10-30 22:10 UTC, denisleuta commented on project/roulette.py
> +    WINNING_BUDGET: int = 1000  # Explicitly declare class attribute
У меня в классе RouletteGame есть функция, которая проверяет кол-во игроков которые банкроты (check_for_winner)

2024-10-30 22:10 UTC, denisleuta commented on project/roulette.py
> +            return bet.amount * 36
Исправил

2024-10-30 22:10 UTC, denisleuta commented on project/roulette.py
> +            return Bet(amount=20, bet_type="color", choice="Green")
Исправил

2024-10-30 22:11 UTC, denisleuta commented on project/roulette.py
> +    def check_for_winner(self) -> Optional[Bot]:
Добавил документацию

2024-10-30 22:11 UTC, denisleuta commented on project/roulette.py
> +    def play_round(self) -> None:
Исправил

2024-10-30 22:13 UTC, denisleuta commented on project/roulette.py
> +        return new_cls
Исправил и в примере продемонстрировал. Еще тестик есть

2024-10-30 22:14 UTC, denisleuta commented on roulette.png
Вроде бы все исправил

2024-10-30 22:14 UTC, denisleuta commented on tests/test_roulette.py
Добавил тесты

2024-11-01 09:10 UTC, Krekep requested changes
Необходимы исправления

2024-11-01 09:10 UTC, Krekep commented on project/bots/aggressive_bot.py
> +class AggressiveBot(Bot, metaclass=StrategyMeta):
Не обязательно указывать metaclass для каждой реализации `Bot`, т.к. нужный метакласс уже указан для `Bot`

2024-11-01 09:10 UTC, Krekep commented on project/bots/aggressive_bot.py
> +    MAX_NUMBER = 49
Кстати, раз уж в документации пишите тип атрибутов, то можете и в коде это указать, к примеру
```
MAX_BUDGET_FOR_NUMBER_BET: int = 50
```

2024-11-01 09:10 UTC, Krekep commented on project/bots/aggressive_bot.py
> +                bet_type="number",
Ну Вы же не избавились от магических констант :(
Можете [тут почитать](https://en.wikipedia.org/wiki/Magic_number_(programming)), чем они плохи

2024-11-01 09:10 UTC, Krekep commented on project/bots/strategic_bot.py
В целом неплохо, а Вы придумали свою стратегию или взяли уже готовую? Не пробовали сравнивать её эффективность с известными?

2024-11-01 09:10 UTC, Krekep commented on project/game/bet.py
> +        choice (Union[str, int]): The specific choice associated with the bet.
Вместо строк лучше использовать перечисления

2024-11-01 09:10 UTC, Krekep commented on project/roulette.py
Хмм, а Вам точно нужен этот файл, с учётом `game_example.py`? В любом случае этот файл не должен находиться в исходниках

2024-11-01 09:10 UTC, Krekep commented on rouletteUML.jpg
1. Конкретные боты наследуют класс `Bot`, поэтому измените тип связи
2. Также лучше уберите связь реализации между ботами и метастратегией и добавьте её между `Bot` и метастратегией. И эта связь должна быть зависимостью, а не реализацией (между игрой и метаигрой тоже)
3. В `RouletteGame` разве метод, к примеру, `spin_wheel` должен быть публичным? В целом проверьте модификаторы видимости у всех полей и методов
4. В коде класса `StrategyMeta` методов больше, чем на диаграмме
5. Нарисуйте стрелочки, пожалуйста, аккуратнее, чем они сейчас изображены (хотя бы в одном стиле)

2024-11-01 09:10 UTC, Krekep commented on tests/test_roulette.py
> +    return game
Было бы круто добавить новую стратегию, а не организовать выбор из уже реализованных. К примеру, в тестах реализовать функцию place_bet (мб ещё что-то), потом собрать словарь для StrategyMeta и создать по факту новый класс, который не реализован в папке bots, но является наследником Bot и реализует все необходимые методы с нетривиальной стратегией. 
Но это так, мысли вслух, необязательное задание

2024-11-07 16:03 UTC, denisleuta commented on project/bots/aggressive_bot.py
> +class AggressiveBot(Bot, metaclass=StrategyMeta):
Убрал

2024-11-07 16:04 UTC, denisleuta commented on project/bots/aggressive_bot.py
> +    MAX_NUMBER = 49
Исправил

2024-11-07 16:04 UTC, denisleuta commented on project/bots/aggressive_bot.py
> +                bet_type="number",
Вот сейчас вроде бы точно везде избавился

2024-11-07 16:04 UTC, denisleuta commented on project/bots/strategic_bot.py
Придумал свою, но сравнивать не пробовал

2024-11-07 16:05 UTC, denisleuta commented on project/game/bet.py
> +        choice (Union[str, int]): The specific choice associated with the bet.
Это у меня не получилось изменить(

2024-11-07 16:05 UTC, denisleuta commented on project/roulette.py
Перенес в папку game

2024-11-07 16:05 UTC, denisleuta commented on rouletteUML.jpg
Переделал UML диаграмму

2024-11-07 16:06 UTC, denisleuta commented on tests/test_roulette.py
> +    return game
Попробовал реализовать что то подобное в тестах

2024-11-09 10:32 UTC, Krekep approved these changes
Зачтено

2024-11-09 10:32 UTC, Krekep commented on UMLroulette.jpg
Что ж Вы одну стрелочку пропустили :(

2024-11-09 10:32 UTC, Krekep commented on tests/test_roulette.py
> +    return RandomBot(name=name, budget=budget)
Не совсем это имелось ввиду, но окей

2024-11-09 10:32 UTC, Krekep commented on project/bots/strategic_bot.py
> +    BET_TYPE_COLOR: str = "color"
Вы пытались. Проблема именно в строковых константах, которые Вы используете везде в коде. У Вас более одного раза встречается color and etc., что плохо, т.к. Вы вероятность ошибиться при написании весьма высока, но отследить такую ошибку очень сложно.
Вместо строк стоило использовать перечисления/классы, к примеру
```
class BetType:
  Color = "color"
  Number = "number"
```
В целом с очень большой натяжкой Ваше решение можно принять

2024-11-09 10:32 UTC, Krekep commented on project/bots/strategic_bot.py
> +            return random.choice(["Red", "Black", "Green"])
У Вас есть `COLOR_GREEN` and etc

2024-11-11 12:37 UTC, merged